FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /src
COPY ["NutritionWebClient.csproj", "./"]
RUN dotnet restore "NutritionWebClient.csproj"
COPY . .
RUN dotnet publish "NutritionWebClient.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY test-ca.crt /usr/local/share/ca-certificates/test-ca.crt
RUN chmod 644 /usr/local/share/ca-certificates/test-ca.crt && update-ca-certificates
ENTRYPOINT ["dotnet","NutritionWebClient.dll"]